### ISSUE TITLE
Unit tests dont compile after pod install

### ISSUE THREAD

**Issue by daniel-hightail** [mmorey/MDMCoreData#28]
If you re-run pod install on the pod file in the example it fails to build the unit tests. This is unfortunate. Also it has a half dependency on UIKit for 2 classes. I would recommend splitting this project up into two pods where one is the UIKit dependent pieces and the other is the core data bits so people can grab what they need without the complex podspec and risk to not being able to build right out of the gates.

**Comment by mmorey** [comment]
> If you re-run pod install on the pod file in the example it fails to build the unit tests. This is unfortunate. 

If you download the repo, open the workspace, and run the unit test they work perfectly fine. As you say, if you re-run pod install the workspace no longer builds thus the unit test don't work. Obviously this used to work so something has changed with the code base or Cocoapods. Do you have any ideas?

> Also it has a half dependency on UIKit for 2 classes. I would recommend splitting this project up into two pods where one is the UIKit dependent pieces and the other is the core data bits so people can grab what they need without the complex podspec and risk to not being able to build right out of the gates.

`MDMCoreData` supports sub-pods which achieve the same thing, right? This allows people to grab exactly what they need and only that.

```ruby
pod "MDMCoreData/MDMPersistenceController"
pod "MDMCoreData/MDMFetchedResultsTableDataSource"
```

Are you suggesting `MDMCoreData` be broken into completely separate pods? Maybe called `MDMCoreDataCore`, `MDMCoreDataiOS`, and `MDMCoreDataOSX`?

**Comment by mmorey** [comment]
@daniel-hightail I have fixed the `pod install` issue. Please pull https://github.com/mmorey/MDMCoreData/tree/cocoapod-fixes and verify.

**Comment by mmorey** [comment]
@daniel-hightail I'm taking your silence to mean the problem has been fixed. If it hasn't please reopen the issue.

**Comment by mmorey** [comment]
[V1.3.4](https://github.com/mmorey/MDMCoreData/releases/tag/1.3.4) with the unit test fix has been pushed to Cocoapods. Thanks!
