### ISSUE TITLE
UITableViewCell does not update if the object property changed is contained in the sort descriptor

### ISSUE THREAD

**Issue by spencerdiniz** [mmorey/MDMCoreData#36]
If the updated property of a managed object is contained in the sort descriptor, the change type is considered "moved" and not "updated". Because of this, the table view does not reload the updated rows.

**According to Apple Docs:**
*A move is reported when the changed attribute on the object is one of the sort descriptors used in the fetch request. An update of the object is assumed in this case, but no separate update message is sent to the delegate.*
[NSFetchedResultsControllerDelegate Protocol Reference](https://developer.apple.com/library/watchos/documentation/CoreData/Reference/NSFetchedResultsControllerDelegate_Protocol/index.html#//apple_ref/occ/intfm/NSFetchedResultsControllerDelegate/controller:didChangeObject:atIndexPath:forChangeType:newIndexPath:)

**Example**
If I have a table view with names that's sorted by the name attribute, if I update the name, the table view does not reload the row, it just moves the row to the appropriate position.

**Comment by mmorey** [comment]
Good catch! Want to submit a pull request so you get some credit?

**Comment by spencerdiniz** [comment]
Sure... Thanks!

**Comment by mmorey** [comment]
Fixed in MDMCoreData 1.5.1.

**Comment by spencerdiniz** [comment]
Updated my project and confirmed! Thanks!
