### ISSUE TITLE
[Question] Context Updating

### ISSUE THREAD

**Issue by woodydaniel** [mmorey/MDMCoreData#40]
Hi,

I'm really struggling with this issue:

I have an object saved in core data. I have a method which updates some properties of that object. I'm using that object's Managed Object Context from `obj.managedObjectContext`.

I change 2 properties: `obj.pending = YES` and `obj.body = 'text'`.
I then save the object back to Core Data as follows:

     if ([managedObjectContext save:&saveError]) {
                
                [persistenceController saveContextAndWait:YES completion:^(NSError *error) {
                     [OfflineManager postData];
                }];
                                
            }

The `postData` method gets all objects from Core Data where the `obj.pending == YES` and posts the data. It's managedObjectContext is of type `NSPrivateQueueConcurrencyType`.

My issue is as follows: The `obj.pending` seems to be updating but the `obj.body` is not. If I add a breakpoint to the app before it posts and restart the app, then the `obj.body` is correctly updated.

If this is a context issue why are some of the object properties' changes being seen and other not?

I've been hacking away at this for hours, any help would be most grateful.

Thanks

**Comment by mmorey** [comment]
Resolved.
